spring:
  application:
    name: grpc-pdf-client
  main:
    banner-mode: console

grpc:
  client:
    service-url: https://primus.local:5555
    output-path: /Volumes/HotRod/output
    write-to-disk: true
    show-enhanced-progress-bar: true
    channel-capacity: 1000
    max-degree-of-parallelism: 8
    progress-update-threshold: 10

logging:
  level:
    com.example.grpcclient: INFO
    io.grpc: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"